#!/bin/bash

get_battery_level() {
    echo $(acpi -b | sed -e "s/[A-Za-z:,-.%]\+//g" | awk 'NR == 1 {print $2}')
}

get_adapter_status() {
    status=$(acpi -b | awk 'NR == 1 {print $3}' | sed -e 's/,//g')
    if [[ $status == "Not" ]]; then 
        echo "Plugged"
        return
    fi
    echo $status
}

echo "{ \"status\":\"$(get_adapter_status)\", \"capacity\": \"$(get_battery_level)\" }"


