"$schema" = 'https://starship.rs/config-schema.json'

format = """
[  ](fg:blue)\
$directory\
$git_status\
$git_branch\

$fill\
$status\
$cmd_duration\
$line_break\
$character\
"""

palette = 'catppuccin_mocha'
# palette = 'tokyo_night'
add_newline = true

[palettes.catppuccin_mocha]
base = '#1e1e2e'
surface = '#313244'
foreground = '#cdd6f4'
background = '#45475a'
current_line = '#45475a'
primary = '#313244'
box = '#2E2E3E'
cyan = '#76E3F6'
green = '#A6E3A1'
orange = '#F9AF74'
pink = '#F5BDE6'
purple = '#CBA6F7'
red = '#F38BA8'
yellow = '#F9E2AF'
status = "#e23140"
blue = "#89b4fa"
mauve = '#cba6f7'


[status]
format = "[](fg:red)[ $status ](fg:red)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[](fg:red)[ $pipestatus ](fg:red)"
disabled = false

[directory]
format = '[󰉋 ](fg:mauve)[$path](bold fg:mauve)'
home_symbol = "~"
truncation_length = 99

[git_branch]
format = '[ on ](fg:foreground)[$symbol](fg:purple)[ $branch](bold fg:purple)'
symbol = ''

[git_status]
format = '[$all_status](fg:green)'
conflicted = ' ='
up_to_date = ''
untracked = ' ?${count}'
stashed = ' $'
modified = ' !${count}'
staged = ' +'
renamed = ' »'
deleted = ' ✘'
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'


[fill]
symbol = ' '
style = 'fg:surface'

[cmd_duration]
min_time = 500
format = '[ ](fg:orange)[ $duration ](fg:orange)'


[character]
format = """
[$symbol](fg:blue) """
success_symbol = '[](fg:bold blue)'
error_symbol = '[](fg:bold red)'
[profiles]
transient = """$character"""