"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭](fg:current_line)\
$status\
$directory\
$git_branch\
$git_status\
$cmd_duration\

$line_break\
$character\
"""

palette = 'catppuccin_mocha'
# palette = 'tokyo_night'
add_newline = true

[palettes.catppuccin_mocha]
foreground = '#f9e2af'
background = '#45475a'
current_line = '#45475a'
primary = '#313244'
box = '#2E2E3E'
blue = '#8AADF4'
cyan = '#76E3F6'
green = '#A6E3A1'
orange = '#F9AF74'
pink = '#F5BDE6'
purple = '#CBA6F7'
red = '#F38BA8'
yellow = '#F9E2AF'
status = "#e23140"

[palettes.tokyo_night]
foreground = '#D8D8D8'
background = '#1A1B26'
current_line = '#2A2C37'
primary = '#292E42'
box = '#2A2C37'
blue = '#7AA2F7'
cyan = '#7FDBCA'
green = '#98C379'
orange = '#FF9E64'
pink = '#FF75A0'
purple = '#BB80B3'
red = '#F7768E'
yellow = '#E5C07B'
status = "#e23140"


[status]
format = "[─](fg:current_line)[](fg:status)[](fg:primary bg:status)[](fg:status bg:box)[ $status](fg:red bg:box)[](fg:box)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[─](fg:current_line)[](fg:status)[](fg:primary bg:status)[](fg:status bg:box)[ $pipestatus](fg:foreground bg:box)[](fg:box)"
disabled = false

[directory]
format = '[─](fg:current_line)[](fg:yellow)[󰷏](fg:primary bg:yellow)[](fg:yellow bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = "~"
truncation_symbol = ''
truncation_length = 2
read_only = ' '
read_only_style = ''

[git_branch]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $branch](fg:green bg:box)'
symbol = ''

[git_status]
format = '[$all_status](fg:green bg:box)[](fg:box)'
conflicted = ' ='
up_to_date = ''
untracked = ' ?${count}'
stashed = ' $'
modified = ' !${count}'
staged = ' +'
renamed = ' »'
deleted = ' ✘'
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'


[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:orange)[](fg:primary bg:orange)[](fg:orange bg:box)[ $duration](fg:foreground bg:box)[](fg:box)'


[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[❯](fg:bold yellow)'
error_symbol = '[❯](fg:bold status)'
[profiles]
transient = """$character"""